# @format

openapi: "3.0.0"
info:
  title: TShirt Store API
  description: FUll fleged eComm Store
  version: 1.0.1
  contact:
    email: panegaiatharva@gmail.com
    url: "https://atharvapanegai.tech"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: For local Host -secure
#   - url: "http://localhost:4000/api/v1"
#     description: For local Host -regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: For local Host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /agni:
    get:
      tags:
        - String
      summary: Returns a greet message from Agni
      responses:
        200:
          description: All good and Success
          content:
            application/json:
              schema:
                type: string
                example: "myString"
        400:
          description: Bad Request
        500:
          description: Internal Server Error
